import { describe, expect, it } from 'vitest';
import * as barrel from '../src/index.js';

/**
 * THE ROOT BARREL RATCHET — the CI fence on a decision already made.
 *
 * DECISION (recorded in docs/design/action-binding-protocol.md): the root
 * barrel is one door too many names wide, and the remedy — subpath doors
 * like `hcifootprint/action`, the way `/react` already is — moves exports,
 * which is breaking. So it is a 3.0 decision, to be SPENT ONCE, not nibbled
 * at. Until then this list keeps the surface from drifting: every addition
 * to the root is a deliberate act that edits this file and answers "why the
 * root, and not a subpath at 3.0?" in its PR. Removals are refused outright
 * — a removal IS the 3.0 move, and it does not happen by accident.
 *
 * This pins the RUNTIME half of the surface (values). Type-only exports are
 * pinned by the API docs gate (`docs:truth`), which fails on undocumented
 * drift there.
 */
// 2.5.0, deliberate: `REQUEST_LIFECYCLE` (a published chart is the point —
// the same table the mover enforces) and `declareLifecycle` (consumers
// build their own enforced charts). Root rather than subpath because both
// are core vocabulary, not a skin; revisit with everything else at 3.0.
// 2.6.0, deliberate, TYPE-ONLY (so filtered out below, listed as the record):
// `ActionTransitionQuery`, `ActionHistoryPolicy`, `ActionEvidenceDeclaration`,
// `ActionReturnOutcome`, `DeclaredContextDeclaration`, `DeclaredContextEntry`,
// `DeclaredContextFold`, `DeclaredContextHandle`, `DeclaredContextSkip`. Why
// the root, and not a subpath at 3.0: the whole Action Binding Protocol is
// served from the root until the 3.0 subpath decision, and splitting one
// feature's types across two doors would be worse. No new runtime value —
// `declareContext` and `transitions` are methods on the runtime.
const ROOT_VALUE_EXPORTS = [
  'ActionTransitionQuery',
  'ActionHistoryPolicy',
  'ActionEvidenceDeclaration',
  'ActionReturnOutcome',
  'DeclaredContextDeclaration',
  'DeclaredContextEntry',
  'DeclaredContextFold',
  'DeclaredContextHandle',
  'DeclaredContextSkip',
  'REQUEST_LIFECYCLE',
  'declareLifecycle',
  'ActionAbandonmentAuthority',
  'ActionAttachment',
  'ActionBindingRef',
  'ActionBindingSnapshot',
  'ActionBindingUpdate',
  'ActionCapture',
  'ActionConnection',
  'ActionContractActivation',
  'ActionDef',
  'ActionDefinitionContract',
  'ActionDefinitionRecord',
  'ActionDefinitionRef',
  'ActionEffectSettlement',
  'ActionEffectSettlementInput',
  'ActionExpectation',
  'ActionGroup',
  'ActionGroupHandle',
  'ActionGuardContract',
  'ActionHandle',
  'ActionHandler',
  'ActionHostAdapter',
  'ActionHostContext',
  'ActionHostListener',
  'ActionHostResolution',
  'ActionHostTargetResolution',
  'ActionHostUnresolvedReason',
  'ActionInputRef',
  'ActionInputSchemaAdapter',
  'ActionInputSchemaContext',
  'ActionInputSchemaResult',
  'ActionInputValidationError',
  'ActionInvocation',
  'ActionInvocationInput',
  'ActionInvocationMiddleware',
  'ActionInvocationMode',
  'ActionInvocationSettlement',
  'ActionInvoke',
  'ActionLateSettlement',
  'ActionLifecycle',
  'ActionObservedInvocation',
  'ActionOffer',
  'ActionOfferFor',
  'ActionOfferRef',
  'ActionPlanManifest',
  'ActionPlanRow',
  'ActionPlanRowStatus',
  'ActionPlanStep',
  'ActionProgress',
  'ActionProgressDeclaration',
  'ActionProgressObservation',
  'ActionProgressSnapshot',
  'ActionRegistry',
  'ActionRuntime',
  'ActionRuntimeOptions',
  'ActionSettleContract',
  'ActionSettlementCapability',
  'ActionTransitionRef',
  'ActionTransitionSnapshot',
  'ActionWalk',
  'ActionWalkRef',
  'ActivationLevel',
  'ActorKind',
  'Actuation',
  'Affordance',
  'AnchorDocument',
  'AnchorElement',
  'AnchorSource',
  'AnchorView',
  'ApprovalResult',
  'AskStatus',
  'Attribution',
  'AttributionBasis',
  'AttributionCertainty',
  'AttributionPolicy',
  'AvailableEdge',
  'AvailableJourney',
  'AvailableSlice',
  'BeginWorkOptions',
  'Binding',
  'BindingCoverage',
  'BindingProjection',
  'BindingRegistration',
  'BlockedBecause',
  'BoundActionOffer',
  'CanonicalRole',
  'CaptureAfter',
  'CaptureBefore',
  'CaptureFailure',
  'Cause',
  'ChannelGap',
  'CommitBundle',
  'CommitJourneyResult',
  'ConcurrencyPolicy',
  'ConfirmReceipts',
  'ConfirmRecord',
  'ConfirmTrailStep',
  'ConfirmWillDo',
  'ConfirmWillUse',
  'ConnectActionOptions',
  'ContextBrief',
  'ContextBriefOptions',
  'ContextfulOptions',
  'DecisionStatus',
  'DeclaredKindCatalog',
  'DefineActionOptions',
  'DefinedAction',
  'DependencyEdge',
  'DirectPrincipal',
  'DoActionArgs',
  'ERROR_MESSAGE',
  'Effect',
  'EffectPolicy',
  'EffectStatus',
  'ElementLocator',
  'Explanation',
  'ExternalObservation',
  'FireOptions',
  'FireResult',
  'FireSettlement',
  'FrameStatus',
  'FreshnessMovement',
  'FreshnessPolicy',
  'FreshnessResponse',
  'GapReason',
  'GapRecord',
  'GraphSource',
  'GraphValidationError',
  'GroundTruth',
  'GroundTruthOptions',
  'GuardRead',
  'HumanApprovalPolicy',
  'HumanDecides',
  'HumanReporting',
  'InputlessActionOffer',
  'InteractionSession',
  'InteractionSessionOptions',
  'Journey',
  'JourneyCallArgs',
  'JourneyDef',
  'JourneyFrame',
  'JourneyMap',
  'JourneyPlan',
  'JourneyPlanStep',
  'JourneySpec',
  'JourneyStanding',
  'JourneyToolsOptions',
  'JourneyToolsPort',
  'JourneyToolsPortWithSettlement',
  'JourneysSource',
  'KindCatalog',
  'KindDeclaration',
  'KindGovernanceReport',
  'KindRecord',
  'LiveAction',
  'LiveActionStore',
  'LiveBindingPort',
  'LiveSource',
  'MCPToolDescription',
  'MapNode',
  'ModalDef',
  'NavigationGraph',
  'NavigationGraphDef',
  'NavigationGraphSpec',
  'NodeDef',
  'NodeKind',
  'NodePathsOf',
  'Observability',
  'ObserveEffectOptions',
  'ObserveEffectResult',
  'OfferRecord',
  'OfferRef',
  'OpenActionOffer',
  'Page',
  'PageDef',
  'PageNodeDef',
  'PendingInfo',
  'PresenceHandle',
  'PresenceIndex',
  'Principal',
  'PrincipalActionPort',
  'PrincipalPolicy',
  'PrincipalPort',
  'REDACTED',
  'ReactRouterOptions',
  'ReadonlyActionDefinitionContract',
  'RedactedFields',
  'RegisterActionGroupOptions',
  'RegisterHandlersOptions',
  'RegisteredActionDef',
  'RegisteredHandlers',
  'Registration',
  'ReportGapOptions',
  'ResolvedActionHost',
  'ResolvedActionHostTarget',
  'RouteObjectLike',
  'RouteStep',
  'RoutedPages',
  'RoutesSource',
  'SenseDeclaration',
  'SensedChange',
  'SensedEffect',
  'SensedEvent',
  'SensedSummary',
  'SensedTrail',
  'ServeResult',
  'Session',
  'SessionEventName',
  'SessionEvents',
  'SessionOptions',
  'Settlement',
  'StaleAcknowledgement',
  'StepStatus',
  'StimulusKind',
  'SurfaceDeclaration',
  'SurfaceHandle',
  'SurfaceQuery',
  'SyncResult',
  'TransitionRecord',
  'TryJourneyPlanResult',
  'UnresolvedActionHost',
  'UnresolvedActionHostTarget',
  'UpdateOptions',
  'UpdateResult',
  'VerifyContract',
  'VerifyFailure',
  'WhereFilter',
  'WorkHandle',
  'WorkRow',
  'actionDefinitionOf',
  'assertBindingCoverage',
  'beginWalk',
  'buildNavigationGraph',
  'composeActionInvocation',
  'connectAction',
  'contextful',
  'createActionRuntime',
  'declareKinds',
  'defineAction',
  'defineJourneyMap',
  'edgesToMCPTools',
  'fromJourneys',
  'fromLiveStore',
  'fromReactRouter',
  'fromRoutes',
  'isBindingCoverage',
  'isDefinedAction',
  'leaveJourneyTool',
  'matchRoute',
  'resolveActionHost',
  'serveToAgent'
].filter((name) => (barrel as Record<string, unknown>)[name] !== undefined);

describe('the root barrel', () => {
  it('serves exactly the recorded surface — growth is deliberate, shrink waits for 3.0', () => {
    const served = Object.keys(barrel).sort();
    expect(served).toEqual([...ROOT_VALUE_EXPORTS].sort());
  });
});
